main: com.forgefrontier.forgefrontier.ForgeFrontier
name: ForgeFrontier
version: 1.0
description: The main plugin for Forge Frontier
api-version: 1.18
depend: [Vault, BentoBox]
libraries:
  - org.postgresql:postgresql:42.5.4
commands:
  gen:
    description: "Command for accessing generators."
  genshop:
    description: "Command for accessing the generator shop."
  shop:
    description: "Command for accessing shop GUI."
  customgive:
    description: "Command for spawning custom items."
  inspect:
    description: "Command used to inspect the statistics of players"
  island:
    description: "Command used for accessing your island GUI."
    aliases:
      - "is"
      - "isl"
  link:
    description: "Command used to connect your Minecraft account to your website account"