"""recipe

Revision ID: 393991fa19ed
Revises: 5674f1f32c0a
Create Date: 2023-04-19 13:45:52.141165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393991fa19ed'
down_revision = '5674f1f32c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('mat1', sa.String(length=50), nullable=True),
    sa.Column('mat2', sa.String(length=50), nullable=True),
    sa.Column('mat3', sa.String(length=50), nullable=True),
    sa.Column('mat4', sa.String(length=50), nullable=True),
    sa.Column('mat5', sa.String(length=50), nullable=True),
    sa.Column('mat6', sa.String(length=50), nullable=True),
    sa.Column('mat7', sa.String(length=50), nullable=True),
    sa.Column('mat8', sa.String(length=50), nullable=True),
    sa.Column('mat9', sa.String(length=50), nullable=True),
    sa.Column('type1', sa.Text(), nullable=True),
    sa.Column('type2', sa.Text(), nullable=True),
    sa.Column('type3', sa.Text(), nullable=True),
    sa.Column('type4', sa.Text(), nullable=True),
    sa.Column('type5', sa.Text(), nullable=True),
    sa.Column('type6', sa.Text(), nullable=True),
    sa.Column('type7', sa.Text(), nullable=True),
    sa.Column('type8', sa.Text(), nullable=True),
    sa.Column('type9', sa.Text(), nullable=True),
    sa.Column('amt1', sa.Integer(), nullable=True),
    sa.Column('amt2', sa.Integer(), nullable=True),
    sa.Column('amt3', sa.Integer(), nullable=True),
    sa.Column('amt4', sa.Integer(), nullable=True),
    sa.Column('amt5', sa.Integer(), nullable=True),
    sa.Column('amt6', sa.Integer(), nullable=True),
    sa.Column('amt7', sa.Integer(), nullable=True),
    sa.Column('amt8', sa.Integer(), nullable=True),
    sa.Column('amt9', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe')
    # ### end Alembic commands ###
