"""feature flags

Revision ID: 72b98a25800e
Revises: ee67a89f3761
Create Date: 2023-04-19 13:20:07.324096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72b98a25800e'
down_revision = 'ee67a89f3761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flags',
    sa.Column('_id', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.drop_table('feature_status')
    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_stats', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tutorial_state', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.drop_column('tutorial_state')
        batch_op.drop_column('base_stats')

    op.create_table('feature_status',
    sa.Column('Key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('JSON_String', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Key', name='feature_status_pkey')
    )
    op.drop_table('feature_flags')
    # ### end Alembic commands ###
