"""recipe edits

Revision ID: 79e96712d407
Revises: 393991fa19ed
Create Date: 2023-04-19 15:24:35.172159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e96712d407'
down_revision = '393991fa19ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('output', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('out_type', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('output_amount', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('output_amount')
        batch_op.drop_column('out_type')
        batch_op.drop_column('output')

    # ### end Alembic commands ###
