"""island_id

Revision ID: 81d37560039a
Revises: 
Create Date: 2023-03-29 14:24:24.828788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d37560039a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bazaar_lookup', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['slot_id'])

    with op.batch_alter_table('bazaar_orders', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['order_id'])

    with op.batch_alter_table('generator_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collected_amount', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('owner_uuid', sa.TEXT(), nullable=True))
        batch_op.alter_column('level',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('last_collection_time',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('location_x',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('location_y',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('location_z',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('location_world',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('generator_id')
        batch_op.drop_column('island_id')

    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['link_id'])

    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id_'])

    with op.batch_alter_table('stash_instances', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id_'])
        batch_op.drop_column('island_id')

    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['player_uuid'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('island_id', sa.TEXT(), nullable=True))
        batch_op.create_unique_constraint(None, ['id_'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('island_id')

    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('stash_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('island_id', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('generator_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('island_id', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('generator_id', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('location_world',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('location_z',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('location_y',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('location_x',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('last_collection_time',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('level',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.drop_column('owner_uuid')
        batch_op.drop_column('collected_amount')

    with op.batch_alter_table('bazaar_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('bazaar_lookup', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
