"""fix

Revision ID: df0149446047
Revises: 81d37560039a
Create Date: 2023-03-29 14:53:33.853894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df0149446047'
down_revision = '81d37560039a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generator_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generator_id', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('island_id', sa.TEXT(), nullable=True))
        batch_op.alter_column('level',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('last_collection_time',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('location_x',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('location_y',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('location_z',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_column('owner_uuid')
        batch_op.drop_column('collected_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generator_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collected_amount', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('owner_uuid', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('location_z',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('location_y',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('location_x',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('last_collection_time',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('level',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.drop_column('island_id')
        batch_op.drop_column('generator_id')

    # ### end Alembic commands ###
