"""island_id

Revision ID: dfe5372547b2
Revises: 9ddd9371221d
Create Date: 2023-03-29 15:02:11.728356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfe5372547b2'
down_revision = '9ddd9371221d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stash_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('island_id', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stash_instances', schema=None) as batch_op:
        batch_op.drop_column('island_id')

    # ### end Alembic commands ###
