"""purchased ranks

Revision ID: ee67a89f3761
Revises: 894359dd6d12
Create Date: 2023-04-19 00:19:26.774527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee67a89f3761'
down_revision = '894359dd6d12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchased_ranks', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('purchased_ranks')

    # ### end Alembic commands ###
