import Head from "next/head";

import {Inter, Raleway} from "@next/font/google";


const inter = Inter({subsets: ["latin"]});
const raleway = Raleway({preload: false})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="../styles/global.css" rel="stylesheet"></link>
      </Head>
      <main className="">
        <div className="global_background full_page">
          <div className="login_super_content vertical_center">
            <p style={raleway.style} className="login_title">Hello World</p>
          </div>
        </div>
      </main>
    </>
  );
}
