import Head from "next/head";

import {Inter, Raleway} from "@next/font/google";
import Login from "./Login";

const inter = Inter({subsets: ["latin"]});
const raleway = Raleway({preload: false})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="../styles/global.css" rel="stylesheet"></link>
      </Head>
      <main>
        {Login()}
      </main>
    </>
  );
}
