import Head from "next/head";
import Link from "next/link";

import {Raleway} from "@next/font/google";

const raleway = Raleway({subsets: ["latin"]});
export default function Home() {
  return (
    <>
      <Head>
        <title>Forge Frontiers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={raleway.style} className="mx-auto text-center mt-8">
        Something cool here soon..
        <br />
        <div>
          <Link className="underline" href="/login">
            Login
          </Link>
        </div>
        <div>
          <Link className="underline" href="/register">
            Register
          </Link>
        </div>
      </main>
    </>
  );
}
